"""Изменение статуса задачи

Revision ID: 38a13617df88
Revises: 5b9b8ede112b
Create Date: 2025-07-24 16:16:44.903851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a13617df88'
down_revision: Union[str, Sequence[str], None] = '5b9b8ede112b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               nullable='None')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
